Script to compile a Python script file that is saved in a specific environment varible with a spcific output.

diff --git a/python-hello_world/101-compile b/python-hello_world/101-compile
--- a/python-hello_world/101-compile
+++ b/python-hello_world/101-compile
@@ -1,7 +1,13 @@
 #!/bin/bash
 
-if [ -v PYFILE ]; then
-  echo 1
-else
-  echo 0
+# Check if PYFILE is set
+if [ -z "$PYFILE" ]; then
+    echo "Error: PYFILE environment variable not set."
+    exit 1
 fi
+
+# Compile the Python file
+python -m py_compile "$PYFILE"
+
+# Rename the output file to add 'c' at the end
+mv "${PYFILE}c" "${PYFILE}c"
